#cloud-config
package_update: true
package_upgrade: true

packages:
  - docker.io
  - docker-compose
  - git
  - curl
  - wget
  - unzip
  - htop
  - fail2ban

users:
  - name: ${admin_username}
    groups: docker, sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

runcmd:
  # Enable and start Docker
  - systemctl enable docker
  - systemctl start docker
  
  # Add admin user to docker group
  - usermod -aG docker ${admin_username}
  
  # Configure fail2ban for SSH protection
  - systemctl enable fail2ban
  - systemctl start fail2ban
  
  # Create discourse directory
  - mkdir -p /var/discourse
  - chown ${admin_username}:${admin_username} /var/discourse
  
  # Set up automatic security updates
  - echo 'Unattended-Upgrade::Automatic-Reboot "false";' >> /etc/apt/apt.conf.d/50unattended-upgrades
  - systemctl enable unattended-upgrades

write_files:
  - path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 3
      
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3
      bantime = 3600

  - path: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }

final_message: "Discourse VM initialization complete"