name: Terraform Validation

on:
  push:
    paths: [ 'infra/terraform/**' ]
  pull_request:
    paths: [ 'infra/terraform/**' ]

env:
  TF_VERSION: "1.6.0"

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Terraform Format Check
      working-directory: infra/terraform
      run: terraform fmt -check -recursive
    
    - name: Terraform Init (validation only)
      working-directory: infra/terraform
      run: terraform init -backend=false
    
    - name: Terraform Validate
      working-directory: infra/terraform
      run: terraform validate
    
    - name: TFLint Setup
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest
    
    - name: TFLint Init
      working-directory: infra/terraform
      run: tflint --init
    
    - name: TFLint Run
      working-directory: infra/terraform
      run: tflint --format compact
    
    - name: Terraform Docs Check
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: infra/terraform
        output-file: README.md
        output-method: inject
        git-push: false
        fail-on-diff: true

  cost-estimation:
    name: Cost Estimation
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}
    
    - name: Generate Infracost JSON
      working-directory: infra/terraform
      run: |
        infracost breakdown --path . \
          --format json \
          --out-file infracost-base.json
    
    - name: Post Infracost comment
      if: github.event_name == 'pull_request'
      run: |
        infracost comment github --path infracost-base.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{ secrets.GITHUB_TOKEN }} \
          --pull-request ${{ github.event.number }} \
          --behavior update